version: "2"
run:
  timeout: 5m
linters:
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - "-QF1008" # exclude 'could remove embedded field "<field>" from selector'
