version: "2"
run:
  timeout: 5m
linters:
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - "-QF1008" # exclude 'could remove embedded field "<field>" from selector'
        - "-ST1000" # exclude 'at least one file in a package should have a package comment'
        - "-ST1003" # exclude 'should not use ALL_CAPS in Go names; use CamelCase instead'
                    # to be fixed 'should not use underscores in Go names'
