# simply run 
# golangci-lint run
# golangci-lint run --fix
# from this directory
# list of linters: https://golangci-lint.run/usage/linters/
# typo apparant
# https://www.elektrotehnika.mk/catalogs/ABB/j/meter/eqmatic_presentation.pdf


version: "2"
run:
  timeout: 5m
linters:
  default: none
  disable:
    - godox # TODO/BUG/FIXME
    - cyclop
    - depguard
    - err113 # do not define dynamic errors, use wrapped static errors instead
    - exhaustruct # knx.GroupEvent is missing fields Source, Data
    - forbidigo
    - forcetypeassert # type assertion must be checked 
    - goconst
    - godot
    - funlen
    - gosec
    - interfacebloat
    - gosmopolitan
    - ireturn # return of interface
    - mnd # magic number
    - nestif
    - nlreturn
    - noctx
    - prealloc
    - unconvert
    - varnamelen
    - gochecknoglobals
    - wrapcheck # https://github.com/tomarrell/wrapcheck
    - gomoddirectives # only using replace in dev
    - gocognit
    - wsl_v5 # empty lines, but toggles too frequently

  enable:
    - funcorder # function order
    - modernize
    - staticcheck
    - errcheck # check errors
    - govet # suspicious constructs
    - ineffassign
    - lll # long lines
    - bodyclose
    - copyloopvar
    - misspell
    - whitespace
    - revive # important for comments

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 2
    revive:
      rules:
        - name: exported
          arguments:
            - "disableChecksOnMethods"
            - "disable-stuttering-check"

